name: deploy server

on:
  push:
    branches: [ "d2jam" ]
    paths:
      - 'net/**'
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make server
      run: make server
      working-directory: net
    - uses: actions/upload-artifact@v7
      with:
        path: net/server
        name: server
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: server
          path: dist/
      - run: ls dist/
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOST }}
          
      - run: "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22222 ubuntu@15.204.212.176 'sudo systemctl stop d2jam4'"
      - run: "scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 22222 dist/server ubuntu@15.204.212.176:/home/ubuntu/."
      - run: "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22222 ubuntu@15.204.212.176 'sudo systemctl start d2jam4'"
